import "./globals.css";
import RecoilRootWrapper from "./recoil/RecoilRootWrapper";

export const metadata = {
  title: "Song Sieve",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <RecoilRootWrapper>
          <main> {children}</main>
        </RecoilRootWrapper>
      </body>
    </html>
  );
}
